### ISSUE TITLE
Documentation on generalized kurtosis values

### ISSUE THREAD

**Issue by aalfons** [AuroreAA/ICS#11]
We decided not to have an argument to scale the generalized kurtosis values so their product is 1, and instead have an argument in function `gen_kurtosis()` that allows to extract the scaled values. This note in the documentation of `ics()` explains why the scaling is useful:

> In principal if S1 and S2 are true scatter matrices the order does not matter. It will just reverse and invert the kurtosis value vector. This is however not true when not both of them are scatter matrices but one or both are shape matrices. In this case the order of the kurtosis values is also reversed, the ratio however then is not 1 but only constant. This is due to the fact that when shape matrices are used, the kurtosis values are only relative ones. Therefore by the default the kurtosis values are standardized such that their product is 1. If no standardization is wanted, the 'stdKurt' argument should be used.

We should add a note in the documentation of `ICS()` about shape matrices, and we should add a similar note to the help file of `gen_kurtosis()` (which in addition explains why the scaling is useful).

**Comment by aalfons** [comment]
@AuroreAA and @klauschN, can you please check this in the help files of `ICS()` and `gen_kurtosis()`?

**Comment by klauschN** [comment]
This looks good to me
