### ISSUE TITLE
Examples in help files

### ISSUE THREAD

**Issue by aalfons** [AuroreAA/ICS#14]
Add help files for new functions: `ICS()`, `gen_kurtosis()`, ...

@AuroreAA and @klauschN, I'd prefer an empirical data set to a simulated one. Any suggestions? Iris data?

**Comment by AuroreAA** [comment]
`iris` data is fine with me but we can use the datasets analyzed in our paper: `crabs` data from `MASS` or `Philips` from `cellWise`. We can also use `HTP` from `ICSOutlier` package.

**Comment by aalfons** [comment]
One thing to consider here is additional dependencies we'd need to put as `Suggests`. The `datasets` (`iris` data) and `MASS` (`crabs` data) package anyway come bundled with `R` so it's not an issue to have them in `Suggests`. For the other packages, we should think about whether it's reasonable for the user to install them just for an example.

**Comment by AuroreAA** [comment]
Sure! So it is really up to you. Do we want several examples or not? 
And I put quite a few examples here in the readme: https://github.com/AuroreAA/ICSClust

**Comment by aalfons** [comment]
Fantastic, thanks. I think that more than one example will be nice, but perhaps it's enough to use two data sets (`iris` and `crabs`)?

**Comment by AuroreAA** [comment]
Indeed I think using two data sets is more than enough.

**Comment by AuroreAA** [comment]
I started to add some examples. Should we add unit tests for the new functions as well?

**Comment by klauschN** [comment]
I am in favor of more examples. Note that we used some artifical examples to demonstrate that one has to look at the first and last components. Most toy data sets often have information only at one "end".
Tests sound also like  good idea.

**Comment by AuroreAA** [comment]
I added the examples from the `ics` function except the one where we compute the scatters first, as we prefer preventing people to do it. 
However I have a warning for the examples with the images (which is cool by the way!): `Warning message:
In rep(cellres, length = 2) : 'x' is NULL so the result will be NULL`
@klauschN can you have a look?

@aalfons do you want to include more examples?

**Comment by klauschN** [comment]
Thanks! Strange that these warnings come now. It seems adding cellres=1 to all pixmapGrey calls does the trick. Though I do not know what this does;-)

I do not dare to write now in the code. So here the version without warning and which seems to give the same output:

plot(pixmapGrey(X.mixed[,1],ncol=p, cellres=1))
plot(pixmapGrey(X.mixed[,2],ncol=p, cellres=1))
plot(pixmapGrey(X.mixed[,3],ncol=p, cellres=1))


plot(pixmapGrey(ics.components(ICA.fig)[,1],ncol=p, cellres=1))
plot(pixmapGrey(ics.components(ICA.fig)[,2],ncol=p, cellres=1))
plot(pixmapGrey(ics.components(ICA.fig)[,3],ncol=p, cellres=1))

**Comment by AuroreAA** [comment]
Thanks! I have made the changes.

**Comment by aalfons** [comment]
I've lost a bit the overview of which help files in the package I was supposed to update with examples. @AuroreAA, do you have the list of all the help files for me that I need to be update?

**Comment by AuroreAA** [comment]
Mainly `ICS()` and all the methods or functions related to it. In fact I already added examples for all functions but at some point, you wanted to do more. So you can have a look and add some if you want.
