### ISSUE TITLE
Fix help file of covW()

### ISSUE THREAD

**Issue by aalfons** [AuroreAA/ICS#15]
The help file of `covW()` doesn't explain what is returned and doesn't have an example.

I noticed this because `roxygen2` complained. @klauschN and @AuroreAA, are there any other help files (not written with `roxygen2` that have missing information?

**Comment by AuroreAA** [comment]
I just forgot to complete the help file. I will do it. 

However, yes there are some functions with missing information like `ICS_scatter`, `components` and `gen_kurtosis`.

**Comment by AuroreAA** [comment]
@klauschN can you check the added documentation of `covW` please?

**Comment by klauschN** [comment]
Hi!
I changed a bit the  help - also tried to make clearer that it is "a" one-step M-estimator as there are almost infinite many options.
