### ISSUE TITLE
Suggests

### ISSUE THREAD

**Issue by AuroreAA** [AuroreAA/ICS#20]
We include the packages 'ICSOutlier', 'ICSClust' but then we have a note: `Packages suggested but not available for checking`.
What should we do? Because `ICSClust` cannot be available until we release the new version of `ICS`.

**Comment by aalfons** [comment]
I see two options:
- We can try to submit both packages at the same time, and add a note *in both submissions* that explains the situation (that whichever one is checked first will give errors/warnings/notes until the other is added, but that everything should be resolved when both are added). They may add both of them after manual inspection, or they will tell us what else to do.
- One way to avoid the discussion is to submit `ICS` first **without** the reference to `ICSClust` in the help file. Then we submit `ICSClust` when the new version of `ICS` is on CRAN. After a few weeks, we can submit a new version of `ICS` that includes the reference to `ICSClust`. The downside is of course that this is a longer process.

**Comment by AuroreAA** [comment]
@klauschN what do you prefer?

**Comment by klauschN** [comment]
Maybe the easiest is to remove the link now and then later add the links
