### ISSUE TITLE
CHANGES file

### ISSUE THREAD

**Issue by AuroreAA** [AuroreAA/ICS#21]
@aalfons anything else to add?

**Comment by aalfons** [comment]
I made a small change that the new implementation uses S3 classes and methods and that it supports different algorithms.

**Comment by aalfons** [comment]
Is there a reason why the change log is in `inst/CHANGES` and not in `NEWS` in the package root directory?

**Comment by AuroreAA** [comment]
I have no idea how is it working, @klauschN?

**Comment by klauschN** [comment]
I have it in all my packages so - there was no news that I am aware of when I started packages...

**Comment by aalfons** [comment]
Having it in `NEWS` has the advantage that it this file is then linked in the package website on CRAN, see e.g. here: <https://cran.r-project.org/package=robmed>

**Comment by aalfons** [comment]
I moved `inst/CHANGES` to `NEWS`, for the above reason. @klauschN, please let me know if this should be reverted.

**Comment by klauschN** [comment]
Fine by me - I am just irritated because earlier the file was shown on the package webpage and now not anymore - and it still works with some other packages of mine...

**Comment by aalfons** [comment]
That is indeed irritating...
