### ISSUE TITLE
Simplify QR algorithm

### ISSUE THREAD

**Issue by AuroreAA** [AuroreAA/ICS#3]
Some ideas from Klaus: 
`apply(Q, 1, function(x) sum(x^2))` could be `rowSums(Q^2) `

` cf*1/n*(n-1)*t(Q) %*% diag(d_i^alpha) %*% Q` should be much simpler the first or second matrix product could be a sweep and then afterwards crossprod could be used.
But that maybe for later bit now I would write `1/n*(n-1) ` as ` (n-1)/n`

Would for `t(U2) %*% t(Rinv) ` be better ` t(Rinv %*% U2) ` 
What about using tcrosspord for ` Xt_row_per[order(order_rows),qr_Xt$pivot]%*%t(B) ` 

Then `Tau %*% t(Pi3) %*% t(Q1) ` could use two tcrossprods, or?

Again saving one transpose: ` t(Pi2) %*% t(X_tilde) ->  t(X_tilde %*% Pi2) `  

Again, `1/n*cf * t( X.centered) %*% diag(di^alpha) %*%  X.centered`  I would make the constant `cf/n` and then probably a sweep for the scaling and then a crossprod.

**Comment by aalfons** [comment]
Row-wise infinity norm `apply(X.c, 1, function(x) max(abs(x)))` can be rewritten `apply(abs(X.c), 1, max)`. Not sure if that save computation time, but the code looks cleaner.

**Comment by aalfons** [comment]
`1/sqrt(n-1)*X_reordered` should be written as `X_reordered / sqrt(n-1)` to avoid unnecessary arithmetic operations.

**Comment by aalfons** [comment]
`X_row_per[order(order_rows), qr_X$pivot]` can be written as `X.c[, qr_X$pivot]`. There's no need to reorder rows back to the original order since `X.c` still has the original order of the rows.

**Comment by aalfons** [comment]
> Would for `t(U2) %*% t(Rinv) ` be better `t(Rinv %*% U2)`

Actually, I think it's better to bypass `Rinv <- qr.solve(R)` altogether and instead use `t(qr.solve(R, U2))`. That should take advantage of the fact that R is is an upper triangular matrix, while `Rinv %*% U2` does a lot of multiplications with 0.

**Comment by aalfons** [comment]
> Then `Tau %*% t(Pi3) %*% t(Q1) ` could use two tcrossprods, or?
> 
> Again saving one transpose: `t(Pi2) %*% t(X_tilde) -> t(X_tilde %*% Pi2)`

I did not find those lines of code in `ICS()`. @AuroreAA , is this from an older version of the function, or are those used in another function? All the other things mentioned in the above discussion are taken care of.

**Comment by AuroreAA** [comment]
I confirmed it is in the function for the HD case which is not considered here.

**Comment by aalfons** [comment]
Thanks. Should we close this issue now or leave it open? I assume the HD case will be included in the package at some point, but that's not what we should spend our time on now.

**Comment by AuroreAA** [comment]
I agree and we can close it then.
