### ISSUE TITLE
Enable QR algorithm for default value of scatter pair

### ISSUE THREAD

**Issue by aalfons** [AuroreAA/ICS#5]
We should figure out a way to enable the QR algorithm in `ICS()` when `S2` is `cov4()` or `ICS_cov4()`, since that corresponds to the default value. In other words, the default choice should still benefit from the numerically more stable algorithm.

Using `covW()` or `ICS_covW()` not only requires the user to make a change, but they also need to know to set argument `cf = 1/(ncol(X)+2)`. That requires a lot of user knowledge to benefit from the QR algorithm for COV-COV4.

**Comment by AuroreAA** [comment]
Here is the correspondence between functions:
- `ics(X, S1 = cov, S2 = cov4,  stdB = "Z", stdKurt = FALSE)` should be converted to `ICS( X, S1 = ICS_cov, S2 =  ICS_covW, S2_args = list(alpha = 1, cf = 1/(ncol(X)+2))`
- `ics(X, S1 = cov, S2 = covAxis,  stdB = "Z", stdKurt = FALSE)` should be converted to `ICS( X, S1 = ICS_cov, S2 =  ICS_covW, S2_args = list(alpha = -1, cf = ncol(X))` 

In fact, only the alpha is really important, the `cf` argument is just a consistency factor.
