### ISSUE TITLE
Generic function components() in package ICtest

### ISSUE THREAD

**Issue by aalfons** [AuroreAA/ICS#7]
The new version of `ICS` defines a generic function `components()`. Package `ICtest`, which of course depends on `ICS` already contains a generic function `components()`. When we release the new version of `ICS`, there also needs to be a new version of `ICtest` that only contains the methods, but not the generic function itself, to avoid a conflict. 

However, the first argument in `ICtest` is called `x`, whereas in `ICS` calls it `object` to be in line with `coef()` and `fitted()` methods. That's not a huge issue, but we should decide what we want to use going forward. @klauschN, what do you think?

**Comment by klauschN** [comment]
Yes, I can remove that function in ICtest. However the dependency of ICtest to ICS is only indirect (ICtest depends on ICSNP which depends on ICS). The idea about components was that in ICS I had ics.components if I recall and then we started having components in all our blind source separation packages. They are then almost all of the class bss.
Again that was not optimal from a design point of view...
But I never understood when in R a generic has input object and when x. And I am not sure which packages use now the components. So I would maybe prefer keeping x. I guess if we have screeplot or plot it also will be x, or?

**Comment by aalfons** [comment]
I guess it has to do with the introduction of the `S3` class system. Some functions that were designed to extract information from higher-level object such as fitted models often use `object`, like`coef()`, `fitted()`, `predict()`. Other functions that also handle low-level objects such as vectors often use `x`, like `print()` and `plot()` (my guess is that some variants of those functions have existed in `S` as non-generics before the `S3` class system). But there doesn't seem to be a clear convention about this. Either way, keeping `x` is fine by me.

On a side note, DESCRIPTION file for `ICtest` lists `ICS` in `Depends` (while `ICSNP` is only under `Imports`), so `ICS` is a direct dependency. If we move the generic function to `ICS`, it will be available at user level also when `ICtest` is loaded.
